export declare abstract class Constants {
    static readonly SIYUAN_VERSION: string;
    static readonly NODE_ENV: string;
    static readonly SIYUAN_APPID: string;
    static readonly ASSETS_ADDRESS: string;
    static readonly PROTYLE_CDN: string;
    static readonly UPLOAD_ADDRESS: string;
    static readonly SERVICE_WORKER_PATH: string;
    static readonly SIYUAN_DROP_FILE: string;
    static readonly SIYUAN_DROP_GUTTER: string;
    static readonly SIYUAN_DROP_TAB: string;
    static readonly SIYUAN_DROP_EDITOR: string;
    static readonly SIYUAN_CMD: string;
    static readonly SIYUAN_GET: string;
    static readonly SIYUAN_EVENT: string;
    static readonly SIYUAN_CONFIG_TRAY: string;
    static readonly SIYUAN_QUIT: string;
    static readonly SIYUAN_HOTKEY: string;
    static readonly SIYUAN_INIT: string;
    static readonly SIYUAN_SEND_WINDOWS: string;
    static readonly SIYUAN_SAVE_CLOSE: string;
    static readonly SIYUAN_AUTO_LAUNCH: string;
    static readonly SIYUAN_OPEN_WORKSPACE: string;
    static readonly SIYUAN_OPEN_URL: string;
    static readonly SIYUAN_OPEN_WINDOW: string;
    static readonly SIYUAN_OPEN_FOLDER: string;
    static readonly SIYUAN_OPEN_FILE: string;
    static readonly SIYUAN_EXPORT_PDF: string;
    static readonly SIYUAN_EXPORT_NEWWINDOW: string;
    static readonly CUSTOM_SY_READONLY: string;
    static readonly CUSTOM_SY_FULLWIDTH: string;
    static readonly CUSTOM_REMINDER_WECHAT: string;
    static readonly CUSTOM_RIFF_DECKS: string;
    static readonly SIZE_SCROLL_TB: number;
    static readonly SIZE_SCROLL_STEP: number;
    static readonly SIZE_LINK_TEXT_MAX: number;
    static readonly SIZE_TOOLBAR_HEIGHT: number;
    static readonly SIZE_GET_MAX = 102400;
    static readonly SIZE_UNDO = 64;
    static readonly SIZE_TITLE = 512;
    static readonly SIZE_EDITOR_WIDTH = 760;
    static readonly SIZE_ZOOM: number[];
    static readonly CB_MOVE_NOLIST = "cb-move-nolist";
    static readonly CB_MOUNT_REMOVE = "cb-mount-remove";
    static readonly CB_GET_APPEND = "cb-get-append";
    static readonly CB_GET_BEFORE = "cb-get-before";
    static readonly CB_GET_UNCHANGEID = "cb-get-unchangeid";
    static readonly CB_GET_HL = "cb-get-hl";
    static readonly CB_GET_FOCUS = "cb-get-focus";
    static readonly CB_GET_FOCUSFIRST = "cb-get-focusfirst";
    static readonly CB_GET_SETID = "cb-get-setid";
    static readonly CB_GET_ALL = "cb-get-all";
    static readonly CB_GET_BACKLINK = "cb-get-backlink";
    static readonly CB_GET_UNUNDO = "cb-get-unundo";
    static readonly CB_GET_SCROLL = "cb-get-scroll";
    static readonly CB_GET_CONTEXT = "cb-get-context";
    static readonly CB_GET_ROOTSCROLL = "cb-get-rootscroll";
    static readonly CB_GET_HTML = "cb-get-html";
    static readonly CB_GET_HISTORY = "cb-get-history";
    static readonly LOCAL_ZOOM = "local-zoom";
    static readonly LOCAL_SEARCHDATA = "local-searchdata";
    static readonly LOCAL_SEARCHKEYS = "local-searchkeys";
    static readonly LOCAL_SEARCHASSET = "local-searchasset";
    static readonly LOCAL_DOCINFO = "local-docinfo";
    static readonly LOCAL_DAILYNOTEID = "local-dailynoteid";
    static readonly LOCAL_HISTORYNOTEID = "local-historynoteid";
    static readonly LOCAL_CODELANG = "local-codelang";
    static readonly LOCAL_FONTSTYLES = "local-fontstyles";
    static readonly LOCAL_EXPORTPDF = "local-exportpdf";
    static readonly LOCAL_EXPORTWORD = "local-exportword";
    static readonly LOCAL_EXPORTIMG = "local-exportimg";
    static readonly LOCAL_BAZAAR = "local-bazaar";
    static readonly LOCAL_PDFTHEME = "local-pdftheme";
    static readonly LOCAL_LAYOUTS = "local-layouts";
    static readonly LOCAL_AI = "local-ai";
    static readonly LOCAL_PLUGINTOPUNPIN = "local-plugintopunpin";
    static readonly LOCAL_FLASHCARD = "local-flashcard";
    static readonly LOCAL_FILEPOSITION = "local-fileposition";
    static readonly LOCAL_DIALOGPOSITION = "local-dialogposition";
    static readonly LOCAL_SESSION_FIRSTLOAD = "local-session-firstload";
    static readonly LOCAL_OUTLINE = "local-outline";
    static readonly DIALOG_OPENCARD = "dialog-opencard";
    static readonly DIALOG_MAKECARD = "dialog-makecard";
    static readonly DIALOG_VIEWCARDS = "dialog-viewcards";
    static readonly DIALOG_DIALYNOTE = "dialog-dialynote";
    static readonly DIALOG_RECENTDOCS = "dialog-recentdocs";
    static readonly DIALOG_SWITCHTAB = "dialog-switchtab";
    static readonly DIALOG_SEARCH = "dialog-search";
    static readonly DIALOG_REPLACE = "dialog-replace";
    static readonly DIALOG_GLOBALSEARCH = "dialog-globalsearch";
    static readonly DIALOG_HISTORYCOMPARE = "dialog-historycompare";
    static readonly DIALOG_ACCESSAUTHCODE = "dialog-accessauthcode";
    static readonly DIALOG_AICUSTOMACTION = "dialog-aicustomaction";
    static readonly DIALOG_AIUPDATECUSTOMACTION = "dialog-aiupdatecustomaction";
    static readonly DIALOG_BACKGROUNDLINK = "dialog-backgroundlink";
    static readonly DIALOG_BACKGROUNDRANDOM = "dialog-backgroundrandom";
    static readonly DIALOG_CHANGELOG = "dialog-changelog";
    static readonly DIALOG_COMMANDPANEL = "dialog-commandpanel";
    static readonly DIALOG_DEACTIVATEUSER = "dialog-deactivateuser";
    static readonly DIALOG_EMOJIS = "dialog-emojis";
    static readonly DIALOG_EXPORTIMAGE = "dialog-exportimage";
    static readonly DIALOG_EXPORTTEMPLATE = "dialog-exporttemplate";
    static readonly DIALOG_EXPORTWORD = "dialog-exportword";
    static readonly DIALOG_HISTORY = "dialog-history";
    static readonly DIALOG_HISTORYDOC = "dialog-historydoc";
    static readonly DIALOG_MOVEPATHTO = "dialog-movepathto";
    static readonly DIALOG_RENAME = "dialog-rename";
    static readonly DIALOG_RENAMEASSETS = "dialog-renameassets";
    static readonly DIALOG_RENAMEBOOKMARK = "dialog-renamebookmark";
    static readonly DIALOG_RENAMETAG = "dialog-renametag";
    static readonly DIALOG_REPLACETYPE = "dialog-replacetype";
    static readonly DIALOG_SAVECRITERION = "dialog-savecriterion";
    static readonly DIALOG_SEARCHTYPE = "dialog-searchtype";
    static readonly DIALOG_SEARCHASSETSTYPE = "dialog-searchassetstype";
    static readonly DIALOG_SETTING = "dialog-setting";
    static readonly DIALOG_SNAPSHOTTAG = "dialog-snapshottag";
    static readonly DIALOG_SNAPSHOTMEMO = "dialog-snapshotmemo";
    static readonly DIALOG_SNIPPETS = "dialog-snippets";
    static readonly DIALOG_SYNCADDCLOUDDIR = "dialog-syncaddclouddir";
    static readonly DIALOG_SYNCCHOOSEDIR = "dialog-syncchoosedir";
    static readonly DIALOG_SYNCCHOOSEDIRECTION = "dialog-syncchoosedirection";
    static readonly DIALOG_TRANSFERBLOCKREF = "dialog-transferblockref";
    static readonly DIALOG_WECHATREMINDER = "dialog-wechatreminder";
    static readonly DIALOG_PASSWORD = "dialog-password";
    static readonly DIALOG_SETPASSWORD = "dialog-setpassword";
    static readonly DIALOG_BOOTSYNCFAILED = "dialog-bootsyncfailed";
    static readonly DIALOG_KERNELFAULT = "dialog-kernelfault";
    static readonly DIALOG_STATEEXCEPTED = "dialog-stateexcepted";
    static readonly DIALOG_ATTR = "dialog-attr";
    static readonly DIALOG_SETCUSTOMATTR = "dialog-setcustomattr";
    static readonly DIALOG_CREATENOTEBOOK = "dialog-createnotebook";
    static readonly DIALOG_NOTEBOOKCONF = "dialog-notebookconf";
    static readonly DIALOG_CREATEWORKSPACE = "dialog-createworkspace";
    static readonly DIALOG_OPENWORKSPACE = "dialog-openworkspace";
    static readonly DIALOG_SAVEWORKSPACE = "dialog-saveworkspace";
    static readonly TIMEOUT_DBLCLICK = 190;
    static readonly TIMEOUT_INPUT = 256;
    static readonly TIMEOUT_LOAD = 300;
    static readonly TIMEOUT_TRANSITION = 300;
    static readonly TIMEOUT_COUNT = 1000;
    static readonly HELP_PATH: {
        zh_CN: string;
        zh_CHT: string;
        en_US: string;
        fr_FR: string;
    };
    static readonly QUICK_DECK_ID = "20230218211946-2kw8jgx";
    static KEYCODELIST: {
        [key: number]: string;
    };
    static readonly SIYUAN_KEYMAP: IKeymap;
    static readonly SIYUAN_EMPTY_LAYOUT: Record<string, unknown>;
    static readonly SIYUAN_DEFAULT_REPLACETYPES: {
        [key: string]: boolean;
    };
    static readonly SIYUAN_IMAGE_VIP: string;
    static readonly SIYUAN_IMAGE_FILE: string;
    static readonly SIYUAN_IMAGE_NOTE: string;
    static readonly SIYUAN_IMAGE_FOLDER: string;
    static readonly SIYUAN_ASSETS_IMAGE: string[];
    static readonly SIYUAN_ASSETS_AUDIO: string[];
    static readonly SIYUAN_ASSETS_VIDEO: string[];
    static readonly SIYUAN_ASSETS_EXTS: string[];
    static readonly SIYUAN_ASSETS_SEARCH: string[];
    static readonly SIYUAN_CONFIG_APPEARANCE_DARK_CODE: string[];
    static readonly SIYUAN_CONFIG_APPEARANCE_LIGHT_CODE: string[];
    static readonly ZWSP: string;
    static readonly INLINE_TYPE: string[];
    static readonly BLOCK_HINT_KEYS: string[];
    static readonly BLOCK_HINT_CLOSE_KEYS: IObject;
    static readonly ALIAS_CODE_LANGUAGES: string[];
    static readonly ANALYTICS_EVT_ON_GET_CONFIG: string;
}
